### ISSUE TITLE
New rows are not inserted at the top of the grid

### ISSUE THREAD

**Issue by frederiktoft** [telerik/ui-for-aspnet-mvc-examples#28]
Issue is related to the following example:
https://github.com/telerik/ui-for-aspnet-mvc-examples/tree/master/window/KendoWindow-Ajax-Form
As the title says, when a new row is made using this method, it is not inserted at the top of the grid. When using the normal built in creation of rows, new rows are inserted at the top until the datasource is refreshed.

**Comment by CecoMilchev** [comment]
In general, the new rows of the Kendo UI Grid are added to the top. When this item is created, it should be added to the database table or collection on the server-side. Since in the majority of the cases, the new item is added as the last item to that collection, the moment the grid is rebound, the items are loaded in the order they are stored on the server-side. Except when there is a sort expression applied.

If you would like the new items to stay always on top simply add them as the first items at the collection to which the grid is bound. Or apply a sort expression to the source.
